### ISSUE TITLE
Accuracy

### ISSUE THREAD

**Issue by gsamyak30** [ANIRUDH-333/Sleep-stage-classification-using-ML-alhgorithms#1]
Hi

Can you give idea that how you have calculated accuracy ? Plz if you can give explanation as well ?

**Comment by ANIRUDH-333** [comment]
Suppose we have a dataset having, say, 100 samples that are labeled. Now, we divide these 100 samples into 2 groups where 1 group is for training our model and the other one is for testing the model. So, first, we train our model with say some 80 samples (80%). Now our model is ready to predict the new data. So, now we input the test data and see the predictions. Since we have 20 samples in our test data, we give those 20 samples and our model gives back the predictions. Suppose 18 samples got predicted correctly and the remaining were wrongly predicted, then our accuracy would be (18/20)*100 = 90%

**Comment by gsamyak30** [comment]
And how do you get confusion matrix like what sort of data or parameters you have passed in the code to get confusion matrix ?

**Comment by ANIRUDH-333** [comment]
Ok.. so about the parameters, as we have the library pandas which have a function crosstab. This makes our lives much easier for many things like confusion matrix. The parameters we passed into that are the labels for the test dataset and the predicted labels. So, we have prediction row-wise and our actual labels column-wise. The headings (like 0,1,2,3,5 in our code) are automatically taken based on the passed parameters (i.e labels of test data and predictions). So, finally in the data cells, it gives us the count of how many labels that we passed in both of the parameters matched. 
Usually, we get a clear picture of working of many functions if we try them out with small matrices. So, you can try crosstab function for some 2 x 2 matrix (i.e 2 column-wise and 2 row-wise).
