### ISSUE TITLE
Confusion Matrix

### ISSUE THREAD

**Issue by gsamyak30** [ANIRUDH-333/Sleep-stage-classification-using-ML-alhgorithms#2]
Hi Anirudh
There are 2 question in my mind like in which file your predicted data is been stored. And how can we get the confusion matrix of svm ?
And at last if you can tell me like how you have get confusion matrix how your each data has been compared and how the confusion matrix of rf and knn are same ?
And the use of mlp and can we get confusion matrix of that as well ?

**Comment by ANIRUDH-333** [comment]
Firstly, we didn't have the requirement to store the predicted and hence we didn't store it. However, you can modify the code and store the data needed. 
Thank for pointing out. The confusion matrix for KNN and RF is not the same. We made a mistake by taking the same variable in both the cases.
In cell 19, line 6, instead of pred, we need to take the y_pred. 
I will update it.
Yes, we can get the confusion matrix for that but we dint include that in our code.

**Comment by gsamyak30** [comment]
In svm the parameter line it showing the x_train is not defined ?
And if we have to get confusion matrix of the svm then what code should we have to write to get it ?

**Comment by ANIRUDH-333** [comment]
Maybe, you are directly trying to run SVM, which might be the reason it is showing, that x_train is not defined. You need to run the 6th cell to define all the train and test sets containing variables.
As of now, I am not sure about the code for producing confusion matrix for multi svm. I will get back to you on this.
